"""
Seed script to populate the VMG database with portfolio company data.

Usage:
    python seed.py

Requires DATABASE_URL environment variable (or uses default from app.config).
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from sqlalchemy.orm import Session
from app.database import engine, SessionLocal, Base
from app.models import Company, Leader, Portfolio, Sector, CompanyStatus


# ---------------------------------------------------------------------------
# Seed data
# ---------------------------------------------------------------------------

COMPANIES = [
    # ── Technology — Software ──
    {
        "name": "Attentive",
        "slug": "attentive",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "AI-powered SMS and email marketing platform for personalized mobile messaging.",
        "category": "SMS & Email Marketing",
        "website": "https://www.attentivemobile.com",
        "domain": "attentivemobile.com",
        "logo_url": "https://logo.clearbit.com/attentivemobile.com",
        "founded_year": 2016,
        "investment_year": 2019,
        "leaders": [
            {"name": "Brian Long", "title": "Co-Founder & Executive Chairman", "linkedin_url": "https://www.linkedin.com/in/brianclong"},
            {"name": "Amit Jhawar", "title": "CEO", "linkedin_url": "https://www.linkedin.com/in/amitjhawar"},
        ],
    },
    {
        "name": "Afresh",
        "slug": "afresh",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "AI-powered fresh food supply chain optimization platform for grocery retailers.",
        "category": "Supply Chain / Grocery Tech",
        "website": "https://www.afresh.com",
        "domain": "afresh.com",
        "logo_url": "https://logo.clearbit.com/afresh.com",
        "founded_year": 2017,
        "investment_year": 2021,
        "leaders": [
            {"name": "Matt Schwartz", "title": "CEO & Co-Founder", "linkedin_url": "https://www.linkedin.com/in/matt-schwartz-0b76a326"},
        ],
    },
    {
        "name": "Auxia",
        "slug": "auxia",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Agentic AI marketing platform for 1:1 customer journey orchestration.",
        "category": "AI Marketing / Personalization",
        "website": "https://www.auxia.io",
        "domain": "auxia.io",
        "logo_url": "https://logo.clearbit.com/auxia.io",
        "founded_year": 2022,
        "investment_year": 2023,
        "leaders": [
            {"name": "Sandeep Menon", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/sandeep-menon-1087901"},
        ],
    },
    {
        "name": "Boulevard",
        "slug": "boulevard",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Client experience platform for appointment-based self-care businesses like salons and spas.",
        "category": "Salon & Spa Management Software",
        "website": "https://www.joinblvd.com",
        "domain": "joinblvd.com",
        "logo_url": "https://logo.clearbit.com/joinblvd.com",
        "founded_year": 2016,
        "investment_year": 2020,
        "leaders": [
            {"name": "Matt Danna", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/mattdanna"},
        ],
    },
    {
        "name": "Claim",
        "slug": "claim",
        "portfolio": "technology",
        "sector": "software",
        "status": "realized",
        "description": "Social rewards app transforming how Gen Z discovers and engages with brands.",
        "category": "Social Commerce / Rewards",
        "website": "https://www.claim.co",
        "domain": "claim.co",
        "logo_url": "https://logo.clearbit.com/claim.co",
        "founded_year": 2021,
        "investment_year": 2024,
        "exit_year": 2026,
        "acquirer": "Wonder Group",
        "leaders": [
            {"name": "Sam Obletz", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/samobletz"},
        ],
    },
    {
        "name": "Daasity",
        "slug": "daasity",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Omnichannel ecommerce analytics platform built for consumer product brands.",
        "category": "Ecommerce Analytics",
        "website": "https://www.daasity.com",
        "domain": "daasity.com",
        "logo_url": "https://logo.clearbit.com/daasity.com",
        "founded_year": 2017,
        "investment_year": 2021,
        "leaders": [
            {"name": "Dan LeBlanc", "title": "CEO & Co-Founder", "linkedin_url": "https://www.linkedin.com/in/ddleblanc"},
        ],
    },
    {
        "name": "Fermat",
        "slug": "fermat",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "AI-powered commerce experience platform for building high-converting shopping experiences.",
        "category": "Commerce Experience Platform",
        "website": "https://www.fermatcommerce.com",
        "domain": "fermatcommerce.com",
        "logo_url": "https://logo.clearbit.com/fermatcommerce.com",
        "founded_year": 2021,
        "investment_year": 2022,
        "leaders": [
            {"name": "Rishabh Jain", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/rishabhmjain"},
        ],
    },
    {
        "name": "Good Face Project",
        "slug": "good-face-project",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "AI-powered cosmetic formulation, regulatory compliance, and innovation platform for beauty brands.",
        "category": "Beauty Tech / Cosmetic Formulation",
        "website": "https://thegoodfaceproject.com",
        "domain": "thegoodfaceproject.com",
        "logo_url": "https://logo.clearbit.com/thegoodfaceproject.com",
        "founded_year": 2018,
        "investment_year": 2022,
        "leaders": [
            {"name": "Iva Teixeira", "title": "CEO & Co-Founder", "linkedin_url": "https://www.linkedin.com/in/iva-yovchev-teixeira"},
        ],
    },
    {
        "name": "Gradial",
        "slug": "gradial",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "AI agent platform that automates enterprise marketing content operations and workflows.",
        "category": "AI Marketing Automation",
        "website": "https://www.gradial.com",
        "domain": "gradial.com",
        "logo_url": "https://logo.clearbit.com/gradial.com",
        "founded_year": 2023,
        "investment_year": 2023,
        "leaders": [
            {"name": "Doug Tallmadge", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/doug-tallmadge-14166075"},
        ],
    },
    {
        "name": "Lyric",
        "slug": "lyric",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "AI platform for supply chain modeling, planning, and autonomous operations.",
        "category": "Supply Chain AI",
        "website": "https://lyric.tech",
        "domain": "lyric.tech",
        "logo_url": "https://logo.clearbit.com/lyric.tech",
        "founded_year": 2022,
        "investment_year": 2022,
        "leaders": [
            {"name": "Ganesh Ramakrishna", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/ganeshatalk"},
        ],
    },
    {
        "name": "Milk Moovement",
        "slug": "milk-moovement",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Dairy supply chain management software tracking raw milk from farm to processor.",
        "category": "Dairy Supply Chain Software",
        "website": "https://www.milkmoovement.com",
        "domain": "milkmoovement.com",
        "logo_url": "https://logo.clearbit.com/milkmoovement.com",
        "founded_year": 2018,
        "investment_year": 2022,
        "leaders": [
            {"name": "Jon King", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/jonathanjking"},
        ],
    },
    {
        "name": "parcelLab",
        "slug": "parcellab",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Post-purchase experience platform for branded order tracking, communication, and returns.",
        "category": "Post-Purchase Experience",
        "website": "https://parcellab.com",
        "domain": "parcellab.com",
        "logo_url": "https://logo.clearbit.com/parcellab.com",
        "founded_year": 2015,
        "investment_year": 2021,
        "leaders": [
            {"name": "Tobias Buxhoidt", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/tobi-buxhoidt-26290498"},
        ],
    },
    {
        "name": "Pray.com",
        "slug": "pray-com",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "The #1 app for daily prayer, faith-based audio content, and spiritual wellness.",
        "category": "Faith & Wellness App",
        "website": "https://www.pray.com",
        "domain": "pray.com",
        "logo_url": "https://logo.clearbit.com/pray.com",
        "founded_year": 2016,
        "investment_year": 2021,
        "leaders": [
            {"name": "Steve Gatena", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/stevegatena"},
        ],
    },
    {
        "name": "Rinsed",
        "slug": "rinsed",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "CRM and membership management platform purpose-built for the car wash industry.",
        "category": "Car Wash CRM / SaaS",
        "website": "https://www.rinsed.com",
        "domain": "rinsed.com",
        "logo_url": "https://logo.clearbit.com/rinsed.com",
        "founded_year": 2019,
        "investment_year": 2022,
        "leaders": [
            {"name": "Austin Esecson", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/austinesecson"},
        ],
    },
    {
        "name": "Shogun",
        "slug": "shogun",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Ecommerce experience platform empowering brands to build high-converting storefronts.",
        "category": "Ecommerce Page Builder",
        "website": "https://getshogun.com",
        "domain": "getshogun.com",
        "logo_url": "https://logo.clearbit.com/getshogun.com",
        "founded_year": 2015,
        "investment_year": 2020,
        "leaders": [
            {"name": "Nick Raushenbush", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/nickraushenbush"},
        ],
    },
    {
        "name": "Specright",
        "slug": "specright",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Cloud-based specification management platform for packaging and supply chain data.",
        "category": "Specification Management",
        "website": "https://www.specright.com",
        "domain": "specright.com",
        "logo_url": "https://logo.clearbit.com/specright.com",
        "founded_year": 2016,
        "investment_year": 2021,
        "leaders": [
            {"name": "Matthew Wright", "title": "Founder & Executive Chairman", "linkedin_url": "https://www.linkedin.com/in/matthew-wright-specright"},
        ],
    },
    {
        "name": "Tracksuit",
        "slug": "tracksuit",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Always-on brand tracking platform making brand awareness measurement accessible and affordable.",
        "category": "Brand Tracking / Market Research",
        "website": "https://www.gotracksuit.com",
        "domain": "gotracksuit.com",
        "logo_url": "https://logo.clearbit.com/gotracksuit.com",
        "founded_year": 2021,
        "investment_year": 2023,
        "leaders": [
            {"name": "Matt Herbert", "title": "Co-Founder & Co-CEO", "linkedin_url": "https://www.linkedin.com/in/herbertmattj"},
            {"name": "Connor Archbold", "title": "Co-Founder & Co-CEO", "linkedin_url": "https://www.linkedin.com/in/connor-archbold"},
        ],
    },
    {
        "name": "Zitcha",
        "slug": "zitcha",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Retail media platform enabling retailers to build and manage advertising networks across all channels.",
        "category": "Retail Media Platform",
        "website": "https://www.zitcha.com",
        "domain": "zitcha.com",
        "logo_url": "https://logo.clearbit.com/zitcha.com",
        "founded_year": 2022,
        "investment_year": 2023,
        "leaders": [
            {"name": "Troy Townsend", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/troytownsend1"},
        ],
    },

    # ── Technology — Marketplaces ──
    {
        "name": "Musely",
        "slug": "musely",
        "portfolio": "technology",
        "sector": "marketplace",
        "status": "realized",
        "description": "Prescription skincare and telehealth platform making dermatological treatments accessible.",
        "category": "Telehealth / Prescription Skincare",
        "website": "https://www.musely.com",
        "domain": "musely.com",
        "logo_url": "https://logo.clearbit.com/musely.com",
        "founded_year": 2012,
        "exit_year": 2023,
        "leaders": [
            {"name": "Jack Jia", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/jack-jia-2923a4"},
        ],
    },
    {
        "name": "Nowsta",
        "slug": "nowsta",
        "portfolio": "technology",
        "sector": "marketplace",
        "status": "active",
        "description": "Workforce management platform for scheduling, time tracking, and payroll for hourly workers.",
        "category": "Workforce Management",
        "website": "https://www.nowsta.com",
        "domain": "nowsta.com",
        "logo_url": "https://logo.clearbit.com/nowsta.com",
        "founded_year": 2015,
        "investment_year": 2021,
        "leaders": [
            {"name": "Nicholas Lillios", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/nicholas-lillios-ba52b8196"},
        ],
    },
    {
        "name": "Nuvemshop",
        "slug": "nuvemshop",
        "portfolio": "technology",
        "sector": "marketplace",
        "status": "active",
        "description": "Latin America's leading ecommerce platform powering 120,000+ online stores across the region.",
        "category": "Ecommerce Platform (LATAM)",
        "website": "https://www.nuvemshop.com.br",
        "domain": "nuvemshop.com.br",
        "logo_url": "https://logo.clearbit.com/nuvemshop.com.br",
        "founded_year": 2011,
        "investment_year": 2021,
        "leaders": [
            {"name": "Santiago Sosa", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/ssosa"},
        ],
    },
    {
        "name": "Swell",
        "slug": "swell",
        "portfolio": "technology",
        "sector": "marketplace",
        "status": "active",
        "description": "API-first headless commerce platform enabling brands to build custom ecommerce experiences.",
        "category": "Headless Commerce Platform",
        "website": "https://www.swell.is",
        "domain": "swell.is",
        "logo_url": "https://logo.clearbit.com/swell.is",
        "founded_year": 2019,
        "investment_year": 2021,
        "leaders": [
            {"name": "Eric Ingram", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/ericingram"},
        ],
    },
    {
        "name": "Weee!",
        "slug": "weee",
        "portfolio": "technology",
        "sector": "marketplace",
        "status": "active",
        "description": "North America's largest Asian and Hispanic online grocery platform delivering authentic foods.",
        "category": "Online Grocery Delivery",
        "website": "https://www.sayweee.com",
        "domain": "sayweee.com",
        "logo_url": "https://logo.clearbit.com/sayweee.com",
        "founded_year": 2015,
        "investment_year": 2021,
        "leaders": [
            {"name": "Larry Liu", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/larrymliu"},
        ],
    },

    # ── Consumer — Beauty & Personal Care ──
    {
        "name": "Drunk Elephant",
        "slug": "drunk-elephant",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Clean-compatible skincare brand known for biocompatible formulations and cult Sephora following.",
        "website": "https://www.drunkelephant.com",
        "domain": "drunkelephant.com",
        "logo_url": "https://logo.clearbit.com/drunkelephant.com",
        "founded_year": 2012,
        "exit_year": 2019,
        "acquirer": "Shiseido",
        "leaders": [
            {"name": "Tiffany Masterson", "title": "Founder & Chief Creative Officer", "linkedin_url": "https://www.linkedin.com/in/tiffanymasterson"},
        ],
    },
    {
        "name": "K18",
        "slug": "k18",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Biotech haircare brand with a patented peptide that molecularly repairs hair damage in 4 minutes.",
        "website": "https://www.k18hair.com",
        "domain": "k18hair.com",
        "logo_url": "https://logo.clearbit.com/k18hair.com",
        "founded_year": 2020,
        "acquirer": "Unilever",
        "leaders": [
            {"name": "Suveen Sahib", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/suveen-sahib"},
        ],
    },
    {
        "name": "Sun Bum",
        "slug": "sun-bum",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Sun care and hair care lifestyle brand inspired by the surf culture of Cocoa Beach, Florida.",
        "website": "https://www.sunbum.com",
        "domain": "sunbum.com",
        "logo_url": "https://logo.clearbit.com/sunbum.com",
        "founded_year": 2010,
        "exit_year": 2019,
        "acquirer": "SC Johnson",
        "leaders": [
            {"name": "Tom Rinks", "title": "Co-Founder & President", "linkedin_url": "https://www.linkedin.com/in/tom-rinks"},
        ],
    },
    {
        "name": "Kosas",
        "slug": "kosas",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Clean makeup brand making skincare-powered cosmetics clinically proven to improve skin health.",
        "website": "https://www.kosas.com",
        "domain": "kosas.com",
        "logo_url": "https://logo.clearbit.com/kosas.com",
        "founded_year": 2015,
        "investment_year": 2021,
        "leaders": [
            {"name": "Sheena Zadeh-Daly", "title": "Founder", "linkedin_url": "https://www.linkedin.com/in/sheena-zadeh-49ab79200"},
        ],
    },
    {
        "name": "Briogeo",
        "slug": "briogeo",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Clean, high-performance haircare brand that pioneered the 'skinification' of hair.",
        "website": "https://www.briogeohair.com",
        "domain": "briogeohair.com",
        "logo_url": "https://logo.clearbit.com/briogeohair.com",
        "founded_year": 2013,
        "exit_year": 2022,
        "acquirer": "Wella",
        "leaders": [
            {"name": "Nancy Twine", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/nancytwine"},
        ],
    },
    {
        "name": "Danessa Myricks Beauty",
        "slug": "danessa-myricks",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Inclusive, innovative color cosmetics brand founded by a veteran makeup artist.",
        "website": "https://www.danessamyricksbeauty.com",
        "domain": "danessamyricksbeauty.com",
        "logo_url": "https://logo.clearbit.com/danessamyricksbeauty.com",
        "founded_year": 2015,
        "investment_year": 2022,
        "leaders": [
            {"name": "Danessa Myricks", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/danessa-myricks-16711a3a"},
        ],
    },
    {
        "name": "Necessaire",
        "slug": "necessaire",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Clean body care brand bringing prestige skincare standards to body wash, lotion, and beyond.",
        "website": "https://www.necessaire.com",
        "domain": "necessaire.com",
        "logo_url": "https://logo.clearbit.com/necessaire.com",
        "founded_year": 2018,
        "investment_year": 2021,
        "leaders": [
            {"name": "Randi Christiansen", "title": "Co-Founder", "linkedin_url": "https://www.linkedin.com/in/randi-christiansen-b631264"},
        ],
    },
    {
        "name": "Snif",
        "slug": "snif",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Direct-to-consumer fragrance brand making high-quality, accessible, non-toxic scents.",
        "website": "https://www.snif.co",
        "domain": "snif.co",
        "logo_url": "https://logo.clearbit.com/snif.co",
        "founded_year": 2020,
        "investment_year": 2022,
        "leaders": [
            {"name": "Bryan Edwards", "title": "Co-Founder & Co-CEO", "linkedin_url": "https://www.linkedin.com/in/edwardsbryan"},
        ],
    },
    {
        "name": "Shani Darden Skin Care",
        "slug": "shani-darden",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Celebrity esthetician-founded clinical skincare line best known for its Retinol Reform serum.",
        "website": "https://www.shanidarden.com",
        "domain": "shanidarden.com",
        "logo_url": "https://logo.clearbit.com/shanidarden.com",
        "founded_year": 2013,
        "investment_year": 2022,
        "leaders": [
            {"name": "Shani Darden", "title": "Founder", "linkedin_url": "https://www.linkedin.com/in/shani-darden-847620a4"},
        ],
    },
    {
        "name": "BeautyStat",
        "slug": "beautystat",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Cosmetic chemist-founded skincare brand with patented stabilized Vitamin C technology.",
        "website": "https://www.beautystat.com",
        "domain": "beautystat.com",
        "logo_url": "https://logo.clearbit.com/beautystat.com",
        "founded_year": 2019,
        "investment_year": 2023,
        "leaders": [
            {"name": "Ron Robinson", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/ronrobinsonbeautystat"},
        ],
    },
    {
        "name": "Colorescience",
        "slug": "colorescience",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Mineral sunscreen and skincare brand that pioneered the first powder mineral sunscreen.",
        "website": "https://www.colorescience.com",
        "domain": "colorescience.com",
        "logo_url": "https://logo.clearbit.com/colorescience.com",
        "founded_year": 2000,
        "acquirer": "RoundTable Healthcare Partners",
        "leaders": [
            {"name": "Diane Ranger", "title": "Founder", "linkedin_url": "https://www.linkedin.com/in/diane-ranger-44595813"},
        ],
    },
    {
        "name": "The Honey Pot Company",
        "slug": "the-honey-pot-company",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Plant-based feminine care brand offering natural, chemical-free hygiene products.",
        "website": "https://www.thehoneypot.co",
        "domain": "thehoneypot.co",
        "logo_url": "https://logo.clearbit.com/thehoneypot.co",
        "founded_year": 2014,
        "investment_year": 2018,
        "exit_year": 2024,
        "acquirer": "Compass Diversified",
        "leaders": [
            {"name": "Beatrice Dixon", "title": "CEO & Co-Founder", "linkedin_url": "https://www.linkedin.com/in/beatrice-dixon"},
        ],
    },

    # ── Consumer — Food & Beverage ──
    {
        "name": "KIND",
        "slug": "kind",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Healthy snack brand known for its whole-ingredient fruit and nut bars and social mission.",
        "website": "https://www.kindsnacks.com",
        "domain": "kindsnacks.com",
        "logo_url": "https://logo.clearbit.com/kindsnacks.com",
        "founded_year": 2004,
        "exit_year": 2020,
        "acquirer": "Mars",
        "leaders": [
            {"name": "Daniel Lubetzky", "title": "Founder & Executive Chairman", "linkedin_url": "https://www.linkedin.com/in/daniellubetzky"},
        ],
    },
    {
        "name": "Justin's",
        "slug": "justins",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Premium nut butter and organic chocolate brand started from a home kitchen in Boulder, Colorado.",
        "website": "https://www.justins.com",
        "domain": "justins.com",
        "logo_url": "https://logo.clearbit.com/justins.com",
        "founded_year": 2004,
        "exit_year": 2016,
        "acquirer": "Hormel",
        "leaders": [
            {"name": "Justin Gold", "title": "Founder", "linkedin_url": "https://www.linkedin.com/in/justin-gold"},
        ],
    },
    {
        "name": "Pirate's Booty",
        "slug": "pirates-booty",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Baked puffed rice and corn snack brand known for its aged white cheddar flavor.",
        "website": "https://www.piratesbooty.com",
        "domain": "piratesbooty.com",
        "logo_url": "https://logo.clearbit.com/piratesbooty.com",
        "founded_year": 1987,
        "exit_year": 2018,
        "acquirer": "Hershey",
        "leaders": [
            {"name": "Robert Ehrlich", "title": "Founder"},
        ],
    },
    {
        "name": "Spindrift",
        "slug": "spindrift",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "First sparkling water brand made with real squeezed fruit, no artificial sweeteners or flavors.",
        "website": "https://www.drinkspindrift.com",
        "domain": "drinkspindrift.com",
        "logo_url": "https://logo.clearbit.com/drinkspindrift.com",
        "founded_year": 2010,
        "exit_year": 2025,
        "acquirer": "Gryphon Investors",
        "leaders": [
            {"name": "Bill Creelman", "title": "Founder & Chairman", "linkedin_url": "https://www.linkedin.com/in/bill-creelman-889b8011"},
        ],
    },
    {
        "name": "Perfect Bar",
        "slug": "perfect-bar",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "The original refrigerated protein bar made with whole food ingredients and a family recipe.",
        "website": "https://www.perfectbar.com",
        "domain": "perfectbar.com",
        "logo_url": "https://logo.clearbit.com/perfectbar.com",
        "founded_year": 2005,
        "exit_year": 2019,
        "acquirer": "Mondelez",
        "leaders": [
            {"name": "Bill Keith", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/bill-keith-48a77a14"},
        ],
    },
    {
        "name": "Quest Nutrition",
        "slug": "quest-nutrition",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "High-protein, low-sugar nutrition brand that became one of the fastest-growing US companies.",
        "website": "https://www.questnutrition.com",
        "domain": "questnutrition.com",
        "logo_url": "https://logo.clearbit.com/questnutrition.com",
        "founded_year": 2010,
        "exit_year": 2019,
        "acquirer": "Simply Good Foods",
        "leaders": [
            {"name": "Tom Bilyeu", "title": "Co-Founder", "linkedin_url": "https://www.linkedin.com/in/thomas-bilyeu-70b15740"},
        ],
    },
    {
        "name": "Ghost",
        "slug": "ghost",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Lifestyle sports nutrition and energy drink brand with licensed flavor collaborations and full label transparency.",
        "website": "https://www.ghostlifestyle.com",
        "domain": "ghostlifestyle.com",
        "logo_url": "https://logo.clearbit.com/ghostlifestyle.com",
        "founded_year": 2016,
        "investment_year": 2022,
        "exit_year": 2024,
        "acquirer": "Keurig Dr Pepper",
        "leaders": [
            {"name": "Dan Lourenco", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/ghostdan"},
        ],
    },
    {
        "name": "Bobbie",
        "slug": "bobbie",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "active",
        "description": "Mom-founded organic infant formula company offering the first European-style formula to meet FDA standards.",
        "website": "https://www.hibobbie.com",
        "domain": "hibobbie.com",
        "logo_url": "https://logo.clearbit.com/hibobbie.com",
        "founded_year": 2018,
        "investment_year": 2022,
        "leaders": [
            {"name": "Laura Modi", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/laurahughes6"},
        ],
    },
    {
        "name": "Milton's Craft Bakers",
        "slug": "miltons",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "active",
        "description": "Craft bakery brand specializing in gluten-free crackers and cauliflower crust pizza.",
        "website": "https://www.miltonscraftbakers.com",
        "domain": "miltonscraftbakers.com",
        "logo_url": "https://logo.clearbit.com/miltonscraftbakers.com",
        "founded_year": 1997,
        "investment_year": 2021,
        "leaders": [],
    },
    {
        "name": "Lily's Sweets",
        "slug": "lilys-sweets",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "No-sugar-added chocolate and confections brand sweetened with stevia and erythritol.",
        "website": "https://www.lilys.com",
        "domain": "lilys.com",
        "logo_url": "https://logo.clearbit.com/lilys.com",
        "founded_year": 2010,
        "exit_year": 2021,
        "acquirer": "Hershey",
        "leaders": [
            {"name": "Cynthia Tice", "title": "Co-Founder", "linkedin_url": "https://www.linkedin.com/in/cynthia-tice-4a87a648"},
        ],
    },
    {
        "name": "Daily Harvest",
        "slug": "daily-harvest",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Plant-based frozen meal delivery service making it easy to eat more sustainably grown produce.",
        "website": "https://www.daily-harvest.com",
        "domain": "daily-harvest.com",
        "logo_url": "https://logo.clearbit.com/daily-harvest.com",
        "founded_year": 2015,
        "exit_year": 2025,
        "acquirer": "Chobani",
        "leaders": [
            {"name": "Rachel Drori", "title": "Founder & Executive Chair", "linkedin_url": "https://www.linkedin.com/in/racheldrori"},
        ],
    },

    # ── Consumer — Wellness & Fitness ──
    {
        "name": "[solidcore]",
        "slug": "solidcore",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "realized",
        "description": "High-intensity, low-impact Pilates-inspired boutique fitness chain with 160+ locations nationwide.",
        "website": "https://www.solidcore.co",
        "domain": "solidcore.co",
        "logo_url": "https://logo.clearbit.com/solidcore.co",
        "founded_year": 2013,
        "investment_year": 2022,
        "exit_year": 2024,
        "acquirer": "L Catterton",
        "leaders": [
            {"name": "Anne Mahlum", "title": "Founder", "linkedin_url": "https://www.linkedin.com/in/anne-mahlum"},
        ],
    },
    {
        "name": "Ancient Nutrition",
        "slug": "ancient-nutrition",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "realized",
        "description": "Superfood supplement brand specializing in bone broth protein, collagen, and regenerative agriculture.",
        "website": "https://www.ancientnutrition.com",
        "domain": "ancientnutrition.com",
        "logo_url": "https://logo.clearbit.com/ancientnutrition.com",
        "founded_year": 2016,
        "exit_year": 2025,
        "acquirer": "Kainos Capital",
        "leaders": [
            {"name": "Jordan Rubin", "title": "Co-Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/jordan-rubin"},
        ],
    },
    {
        "name": "Goli Nutrition",
        "slug": "goli",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "realized",
        "description": "Supplement brand that created the world's first apple cider vinegar gummy vitamin.",
        "website": "https://www.goli.com",
        "domain": "goli.com",
        "logo_url": "https://logo.clearbit.com/goli.com",
        "founded_year": 2018,
        "leaders": [
            {"name": "Michael Bitensky", "title": "Founder", "linkedin_url": "https://www.linkedin.com/in/michaelbitensky"},
        ],
    },
    {
        "name": "ETS Performance",
        "slug": "ets-performance",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "active",
        "description": "Elite athletic performance training company with 30+ facilities producing college and pro athletes.",
        "website": "https://www.etsperformance.com",
        "domain": "etsperformance.com",
        "logo_url": "https://logo.clearbit.com/etsperformance.com",
        "founded_year": 2010,
        "investment_year": 2023,
        "leaders": [
            {"name": "Ryan Englebert", "title": "Founder & President", "linkedin_url": "https://www.linkedin.com/in/ryanenglebert"},
        ],
    },
    {
        "name": "Vega",
        "slug": "vega",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "realized",
        "description": "Plant-based nutrition brand offering protein powders and supplements, co-founded by a pro triathlete.",
        "website": "https://www.myvega.com",
        "domain": "myvega.com",
        "logo_url": "https://logo.clearbit.com/myvega.com",
        "founded_year": 2004,
        "acquirer": "Danone",
        "leaders": [
            {"name": "Brendan Brazier", "title": "Co-Founder", "linkedin_url": "https://www.linkedin.com/in/brendan-brazier-9508921b"},
        ],
    },

    # ── Consumer — Pet ──
    {
        "name": "Maev",
        "slug": "maev",
        "portfolio": "consumer",
        "sector": "pet",
        "status": "active",
        "description": "Human-grade raw dog food brand delivering flash-frozen, whole-ingredient meals.",
        "website": "https://www.meetmaev.com",
        "domain": "meetmaev.com",
        "logo_url": "https://logo.clearbit.com/meetmaev.com",
        "founded_year": 2019,
        "investment_year": 2022,
        "leaders": [
            {"name": "Katie Spies", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/katie-spies"},
        ],
    },
    {
        "name": "Scenthound",
        "slug": "scenthound",
        "portfolio": "consumer",
        "sector": "pet",
        "status": "active",
        "description": "Membership-based dog wellness franchise providing routine hygiene and preventative care.",
        "website": "https://www.scenthound.com",
        "domain": "scenthound.com",
        "logo_url": "https://logo.clearbit.com/scenthound.com",
        "founded_year": 2015,
        "investment_year": 2022,
        "leaders": [
            {"name": "Tim Vogel", "title": "Founder & CEO", "linkedin_url": "https://www.linkedin.com/in/timvogel"},
        ],
    },
    {
        "name": "Natural Balance",
        "slug": "natural-balance",
        "portfolio": "consumer",
        "sector": "pet",
        "status": "realized",
        "description": "Premium natural pet food brand offering limited ingredient diets for dogs and cats.",
        "website": "https://www.naturalbalanceinc.com",
        "domain": "naturalbalanceinc.com",
        "logo_url": "https://logo.clearbit.com/naturalbalanceinc.com",
        "founded_year": 1989,
        "leaders": [],
    },
    {
        "name": "Solid Gold",
        "slug": "solid-gold",
        "portfolio": "consumer",
        "sector": "pet",
        "status": "realized",
        "description": "America's first holistic pet food brand, pioneering natural dog and cat nutrition since 1974.",
        "website": "https://www.solidgoldpet.com",
        "domain": "solidgoldpet.com",
        "logo_url": "https://logo.clearbit.com/solidgoldpet.com",
        "founded_year": 1974,
        "leaders": [],
    },
    {
        "name": "Waggin' Train",
        "slug": "waggin-train",
        "portfolio": "consumer",
        "sector": "pet",
        "status": "realized",
        "description": "Premium all-natural, all-meat pet treats brand.",
        "website": "https://www.adipet.com",
        "domain": "adipet.com",
        "logo_url": "https://logo.clearbit.com/adipet.com",
        "founded_year": 2000,
        "exit_year": 2010,
        "acquirer": "Nestlé Purina",
        "leaders": [],
    },

    # ── Consumer — Food & Beverage (additional realized) ──
    {
        "name": "SkinMedica",
        "slug": "skinmedica",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Clinical skincare brand specializing in anti-aging and skin rejuvenation treatments.",
        "website": "https://www.skinmedica.com",
        "domain": "skinmedica.com",
        "logo_url": "https://logo.clearbit.com/skinmedica.com",
        "founded_year": 1999,
        "exit_year": 2012,
        "acquirer": "Allergan",
        "leaders": [],
    },
    {
        "name": "The Snack Factory",
        "slug": "snack-factory",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Snack brand known for pretzel crisps, bagel chips, and pita chips.",
        "website": "https://www.snackfactory.com",
        "domain": "snackfactory.com",
        "logo_url": "https://logo.clearbit.com/snackfactory.com",
        "founded_year": 2004,
        "exit_year": 2012,
        "acquirer": "Snyder's-Lance",
        "leaders": [],
    },
    {
        "name": "Bare Snacks",
        "slug": "bare-snacks",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Baked fruit and vegetable snack brand serving health-conscious consumers.",
        "website": "https://www.baresnacks.com",
        "domain": "baresnacks.com",
        "logo_url": "https://logo.clearbit.com/baresnacks.com",
        "founded_year": 2001,
        "exit_year": 2018,
        "acquirer": "PepsiCo",
        "leaders": [],
    },
    {
        "name": "Nature's Bakery",
        "slug": "natures-bakery",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Wholesome snack brand baking fruit and grain bars with simple, real ingredients.",
        "website": "https://www.naturesbakery.com",
        "domain": "naturesbakery.com",
        "logo_url": "https://logo.clearbit.com/naturesbakery.com",
        "founded_year": 2011,
        "exit_year": 2020,
        "acquirer": "KIND Snacks",
        "leaders": [],
    },
    {
        "name": "Stone Brewing",
        "slug": "stone-brewing",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Independent craft brewery known for bold, hop-forward beers.",
        "website": "https://www.stonebrewing.com",
        "domain": "stonebrewing.com",
        "logo_url": "https://logo.clearbit.com/stonebrewing.com",
        "founded_year": 1996,
        "exit_year": 2022,
        "acquirer": "Sapporo Breweries",
        "leaders": [],
    },
    {
        "name": "Ilegal Mezcal",
        "slug": "ilegal-mezcal",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Handcrafted mezcal brand using traditional Oaxacan distillation methods.",
        "website": "https://www.ilegalmezcal.com",
        "domain": "ilegalmezcal.com",
        "logo_url": "https://logo.clearbit.com/ilegalmezcal.com",
        "founded_year": 2010,
        "exit_year": 2023,
        "acquirer": "Bacardi",
        "leaders": [],
    },
    {
        "name": "Health Warrior",
        "slug": "health-warrior",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Chia seed-based nutrition bar and snack brand.",
        "website": "https://www.healthwarrior.com",
        "domain": "healthwarrior.com",
        "logo_url": "https://logo.clearbit.com/healthwarrior.com",
        "founded_year": 2011,
        "exit_year": 2018,
        "acquirer": "PepsiCo",
        "leaders": [],
    },
    {
        "name": "Humm Kombucha",
        "slug": "humm-kombucha",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Kombucha brewer offering seasonal and flavored probiotic beverages.",
        "website": "https://www.hummkombucha.com",
        "domain": "hummkombucha.com",
        "logo_url": "https://logo.clearbit.com/hummkombucha.com",
        "founded_year": 2009,
        "exit_year": 2024,
        "acquirer": "SYSTM Foods",
        "leaders": [],
    },
    {
        "name": "Kernel Season's",
        "slug": "kernel-seasons",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Popcorn seasoning brand offering 20+ flavors sold in 15,000+ stores.",
        "website": "https://www.kernelseasons.com",
        "domain": "kernelseasons.com",
        "logo_url": "https://logo.clearbit.com/kernelseasons.com",
        "founded_year": 1999,
        "exit_year": 2020,
        "acquirer": "Sauer Brands",
        "leaders": [],
    },
    {
        "name": "Mighty Leaf Tea",
        "slug": "mighty-leaf-tea",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Premium whole tea leaf brand offering hand-stitched tea pouches.",
        "website": "https://www.mightyleaf.com",
        "domain": "mightyleaf.com",
        "logo_url": "https://logo.clearbit.com/mightyleaf.com",
        "founded_year": 1996,
        "exit_year": 2014,
        "acquirer": "Peet's Coffee",
        "leaders": [],
    },
    {
        "name": "Nutpods",
        "slug": "nutpods",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Plant-based dairy-free creamer brand made from almonds, oats, and coconuts.",
        "website": "https://www.nutpods.com",
        "domain": "nutpods.com",
        "logo_url": "https://logo.clearbit.com/nutpods.com",
        "founded_year": 2013,
        "exit_year": 2023,
        "acquirer": "MidOcean Partners",
        "leaders": [],
    },
    {
        "name": "Popchips",
        "slug": "popchips",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Popped potato chip brand offering low-fat, never-fried snacks.",
        "website": "https://www.popchips.com",
        "domain": "popchips.com",
        "logo_url": "https://logo.clearbit.com/popchips.com",
        "founded_year": 2007,
        "exit_year": 2022,
        "acquirer": "Clearlake Capital",
        "leaders": [],
    },
    {
        "name": "Smashmallow",
        "slug": "smashmallow",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Organic marshmallow snack brand made with natural ingredients.",
        "website": "https://www.smashmallow.com",
        "domain": "smashmallow.com",
        "logo_url": "https://logo.clearbit.com/smashmallow.com",
        "founded_year": 2016,
        "leaders": [],
    },
    {
        "name": "Vermont Smoke & Cure",
        "slug": "vermont-smoke-cure",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Artisanal smoked meats and meat snacks brand based in Vermont.",
        "website": "https://www.vermontsmokeandcure.com",
        "domain": "vermontsmokeandcure.com",
        "logo_url": "https://logo.clearbit.com/vermontsmokeandcure.com",
        "founded_year": 1962,
        "exit_year": 2020,
        "acquirer": "Johnsonville",
        "leaders": [],
    },
    {
        "name": "Stone Distributing",
        "slug": "stone-distributing",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Craft beverage distribution company serving independent brands.",
        "website": "https://www.stonedistributing.com",
        "domain": "stonedistributing.com",
        "logo_url": "https://logo.clearbit.com/stonedistributing.com",
        "founded_year": 1996,
        "exit_year": 2025,
        "acquirer": "Hand Family Companies",
        "leaders": [],
    },
    {
        "name": "Lantana",
        "slug": "lantana",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Bean-based hummus brand using different beans and vegetables for nutrient-rich dips.",
        "website": "https://lantanaproducts.com",
        "domain": "lantanaproducts.com",
        "logo_url": "https://logo.clearbit.com/lantanaproducts.com",
        "founded_year": 2010,
        "exit_year": 2018,
        "leaders": [],
    },

    # ── Consumer — Beauty & Personal Care (additional realized) ──
    {
        "name": "BabyGanics",
        "slug": "babyganics",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Plant-derived personal and home care products for babies and kids.",
        "website": "https://www.babyganics.com",
        "domain": "babyganics.com",
        "logo_url": "https://logo.clearbit.com/babyganics.com",
        "founded_year": 2002,
        "exit_year": 2016,
        "acquirer": "SC Johnson",
        "leaders": [],
    },
    {
        "name": "Hello Bello",
        "slug": "hello-bello",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Plant-based baby care brand offering premium diapers, wipes, and personal care products.",
        "website": "https://www.hellobello.com",
        "domain": "hellobello.com",
        "logo_url": "https://logo.clearbit.com/hellobello.com",
        "founded_year": 2018,
        "exit_year": 2023,
        "acquirer": "Hildred Capital",
        "leaders": [],
    },
    {
        "name": "Yatsen Global",
        "slug": "yatsen-global",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Chinese beauty conglomerate operating color cosmetics and skincare brands.",
        "website": "https://www.yatsenglobal.com",
        "domain": "yatsenglobal.com",
        "logo_url": "https://logo.clearbit.com/yatsenglobal.com",
        "founded_year": 2016,
        "exit_year": 2020,
        "leaders": [],
    },

    # ── Consumer — Wellness & Fitness (additional realized) ──
    {
        "name": "Crunch Holdings",
        "slug": "crunch-holdings",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "realized",
        "description": "Gym and fitness chain with locations nationwide offering affordable memberships.",
        "website": "https://www.crunch.com",
        "domain": "crunch.com",
        "logo_url": "https://logo.clearbit.com/crunch.com",
        "founded_year": 1989,
        "exit_year": 2025,
        "acquirer": "Leonard Green & Partners",
        "leaders": [],
    },
    {
        "name": "Pill Club",
        "slug": "pill-club",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "realized",
        "description": "Online birth control prescription and delivery service simplifying access to reproductive health.",
        "website": "https://www.thepillclub.com",
        "domain": "thepillclub.com",
        "logo_url": "https://logo.clearbit.com/thepillclub.com",
        "founded_year": 2014,
        "exit_year": 2024,
        "acquirer": "TwentyEight",
        "leaders": [],
    },
    {
        "name": "TerraVia",
        "slug": "terravia",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "realized",
        "description": "Algae-based food and nutrition ingredient producer.",
        "website": "https://www.terravia.com",
        "domain": "terravia.com",
        "logo_url": "https://logo.clearbit.com/terravia.com",
        "founded_year": 2003,
        "exit_year": 2017,
        "acquirer": "Corbion",
        "leaders": [],
    },
    {
        "name": "Ampla",
        "slug": "ampla",
        "portfolio": "technology",
        "sector": "software",
        "status": "realized",
        "description": "Growth capital and working capital platform for omnichannel consumer brands.",
        "category": "Financial Services / Lending",
        "website": "https://www.getampla.com",
        "domain": "getampla.com",
        "logo_url": "https://logo.clearbit.com/getampla.com",
        "founded_year": 2019,
        "investment_year": 2021,
        "exit_year": 2025,
        "acquirer": "FundThrough",
        "leaders": [],
    },

    # ── Consumer — Other (additional realized) ──
    {
        "name": "Speck Products",
        "slug": "speck-products",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Consumer electronics accessories brand specializing in protective cases.",
        "website": "https://www.speckproducts.com",
        "domain": "speckproducts.com",
        "logo_url": "https://logo.clearbit.com/speckproducts.com",
        "founded_year": 2001,
        "exit_year": 2021,
        "acquirer": "Telementum",
        "leaders": [],
    },
    {
        "name": "Timbuk2",
        "slug": "timbuk2",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Bags and accessories brand known for messenger bags and custom designs.",
        "website": "https://www.timbuk2.com",
        "domain": "timbuk2.com",
        "logo_url": "https://logo.clearbit.com/timbuk2.com",
        "founded_year": 1989,
        "exit_year": 2019,
        "acquirer": "Exemplis",
        "leaders": [],
    },
    {
        "name": "Pour La Victoire",
        "slug": "pour-la-victoire",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "Designer footwear brand offering contemporary luxury shoes with Italian leathers.",
        "website": "https://www.plvshoes.com",
        "domain": "plvshoes.com",
        "logo_url": "https://logo.clearbit.com/plvshoes.com",
        "founded_year": 2007,
        "leaders": [],
    },
    {
        "name": "Treat",
        "slug": "treat",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "realized",
        "description": "AI-powered customer data platform helping brands manage and personalize customer interactions.",
        "website": "https://www.trytreat.ai",
        "domain": "trytreat.ai",
        "logo_url": "https://logo.clearbit.com/trytreat.ai",
        "founded_year": 2019,
        "exit_year": 2024,
        "acquirer": "Typeface",
        "leaders": [],
    },

    # ── Additional PitchBook Companies ──
    {
        "name": "Cocolab",
        "slug": "cocolab",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Personal care brand focused on coconut-derived beauty and wellness products.",
        "category": "Personal Products",
        "investment_year": 2025,
        "leaders": [],
    },
    {
        "name": "Enlightened",
        "slug": "enlightened",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "active",
        "description": "Better-for-you ice cream and frozen treats brand with high protein and low sugar.",
        "category": "Food Products",
        "website": "https://www.eatenlightened.com",
        "domain": "eatenlightened.com",
        "logo_url": "https://logo.clearbit.com/eatenlightened.com",
        "investment_year": 2025,
        "leaders": [],
    },
    {
        "name": "Tone",
        "slug": "tone",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Personal care brand redefining inclusive beauty products.",
        "category": "Personal Products",
        "investment_year": 2025,
        "leaders": [],
    },
    {
        "name": "Jersey Strong",
        "slug": "jersey-strong",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "active",
        "description": "Fitness and gym chain operating locations across New Jersey.",
        "category": "Fitness & Gyms",
        "website": "https://www.jerseystrong.com",
        "domain": "jerseystrong.com",
        "logo_url": "https://logo.clearbit.com/jerseystrong.com",
        "investment_year": 2024,
        "leaders": [],
    },
    {
        "name": "Ghetto Gastro",
        "slug": "ghetto-gastro",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "active",
        "description": "Bronx-born culinary collective creating culturally inspired food products.",
        "category": "Food Products",
        "website": "https://www.ghettogastro.com",
        "domain": "ghettogastro.com",
        "logo_url": "https://logo.clearbit.com/ghettogastro.com",
        "investment_year": 2024,
        "leaders": [],
    },
    {
        "name": "Melanin Haircare",
        "slug": "melanin-haircare",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Textured hair care brand founded by twin sisters Whitney and Trina White.",
        "category": "Personal Products",
        "investment_year": 2023,
        "leaders": [],
    },
    {
        "name": "Mantra Health",
        "slug": "mantra-health",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Digital mental health platform providing college students access to psychiatry and therapy.",
        "category": "Healthcare Services",
        "website": "https://www.mantrahealth.com",
        "domain": "mantrahealth.com",
        "logo_url": "https://logo.clearbit.com/mantrahealth.com",
        "founded_year": 2018,
        "investment_year": 2022,
        "leaders": [],
    },
    {
        "name": "Cotiss",
        "slug": "cotiss",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Enterprise software platform for business productivity and workflow optimization.",
        "category": "Business/Productivity Software",
        "investment_year": 2022,
        "leaders": [],
    },
    {
        "name": "Expedock",
        "slug": "expedock",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "AI-powered document processing platform for freight forwarding and logistics.",
        "category": "Business/Productivity Software",
        "website": "https://www.expedock.com",
        "domain": "expedock.com",
        "logo_url": "https://logo.clearbit.com/expedock.com",
        "investment_year": 2022,
        "leaders": [],
    },
    {
        "name": "Redbud Brands",
        "slug": "redbud-brands",
        "portfolio": "technology",
        "sector": "software",
        "status": "active",
        "description": "Brand aggregator and media platform for emerging consumer brands.",
        "category": "Media & Information Services",
        "investment_year": 2021,
        "leaders": [],
    },
    {
        "name": "AQUIS",
        "slug": "aquis",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Hair care brand known for water-wicking technology towels and hair products.",
        "category": "Personal Products",
        "website": "https://www.aquis.com",
        "domain": "aquis.com",
        "logo_url": "https://logo.clearbit.com/aquis.com",
        "investment_year": 2021,
        "leaders": [],
    },
    {
        "name": "OVME",
        "slug": "ovme",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "active",
        "description": "Medical aesthetics platform providing accessible cosmetic treatments.",
        "category": "Clinics / Outpatient Services",
        "website": "https://www.ovme.com",
        "domain": "ovme.com",
        "logo_url": "https://logo.clearbit.com/ovme.com",
        "investment_year": 2021,
        "leaders": [],
    },
    {
        "name": "Rowan",
        "slug": "rowan",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Ear piercing and jewelry brand with studio locations and at-home services.",
        "category": "Accessories",
        "website": "https://www.heyrowan.com",
        "domain": "heyrowan.com",
        "logo_url": "https://logo.clearbit.com/heyrowan.com",
        "investment_year": 2021,
        "leaders": [],
    },
    {
        "name": "Monument",
        "slug": "monument",
        "portfolio": "consumer",
        "sector": "wellness",
        "status": "active",
        "description": "Online alcohol treatment platform providing personalized care and medication.",
        "category": "Clinics / Outpatient Services",
        "website": "https://www.joinmonument.com",
        "domain": "joinmonument.com",
        "logo_url": "https://logo.clearbit.com/joinmonument.com",
        "investment_year": 2021,
        "leaders": [],
    },
    {
        "name": "Little Freddie",
        "slug": "little-freddie",
        "portfolio": "consumer",
        "sector": "food-bev",
        "status": "active",
        "description": "Premium organic baby food brand popular in Asia-Pacific markets.",
        "category": "Food Products",
        "website": "https://www.littlefreddie.com",
        "domain": "littlefreddie.com",
        "logo_url": "https://logo.clearbit.com/littlefreddie.com",
        "investment_year": 2018,
        "leaders": [],
    },
    {
        "name": "Proudly",
        "slug": "proudly",
        "portfolio": "consumer",
        "sector": "beauty",
        "status": "active",
        "description": "Clean baby care brand formulated specifically for melanin-rich skin.",
        "category": "Personal Products",
        "leaders": [],
    },
]


# ---------------------------------------------------------------------------
# Seed logic
# ---------------------------------------------------------------------------

SECTOR_MAP = {v.value: v for v in Sector}
PORTFOLIO_MAP = {v.value: v for v in Portfolio}
STATUS_MAP = {v.value: v for v in CompanyStatus}


UPDATABLE_FIELDS = [
    "name", "portfolio", "sector", "status", "description", "website",
    "logo_url", "domain", "investment_year", "exit_year", "acquirer",
    "founded_year", "hq_location", "category",
]


def seed():
    Base.metadata.create_all(bind=engine)

    db: Session = SessionLocal()
    created = 0
    updated = 0
    unchanged = 0

    try:
        for data in COMPANIES:
            leaders_data = data.pop("leaders")

            # Convert string enum values to enum instances
            data["portfolio"] = PORTFOLIO_MAP[data["portfolio"]]
            data["sector"] = SECTOR_MAP[data["sector"]]
            data["status"] = STATUS_MAP[data["status"]]

            existing = db.query(Company).filter(Company.slug == data["slug"]).first()
            if existing:
                # Update any fields that changed
                changed = False
                for field in UPDATABLE_FIELDS:
                    if field not in data:
                        continue
                    new_val = data[field]
                    old_val = getattr(existing, field)
                    if new_val != old_val:
                        setattr(existing, field, new_val)
                        changed = True
                if changed:
                    updated += 1
                else:
                    unchanged += 1
            else:
                company = Company(**data)
                db.add(company)
                db.flush()

                for ld in leaders_data:
                    leader = Leader(company_id=company.id, **ld)
                    db.add(leader)

                created += 1

        db.commit()
        print(f"Seed complete: {created} created, {updated} updated, {unchanged} unchanged.")
        print(f"Total in database: {db.query(Company).count()} companies, {db.query(Leader).count()} leaders.")
    except Exception as e:
        db.rollback()
        print(f"Seed failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
