"""Seed pipeline deals with realistic prospective deal data."""
import uuid
from datetime import datetime, timedelta
import random

from app.database import SessionLocal
from app.models import PipelineDeal

random.seed(42)

DEALS = [
    # Screening stage - early prospects
    {
        "company_name": "Glow Republic",
        "sector": "beauty",
        "strategy": "consumer",
        "stage": "screening",
        "description": "DTC clean skincare brand targeting Gen Z. Viral TikTok presence with 2M+ followers. Strong repeat purchase rates.",
        "deal_size": 45_000_000,
        "valuation": 180_000_000,
        "revenue": 32_000_000,
        "growth_rate": 85,
        "source": "Proprietary sourcing",
        "lead_contact": "Sarah Chen",
        "priority": "high",
        "notes": "Founder call scheduled. Strong brand with authentic community.",
        "days_ago": 5,
    },
    {
        "company_name": "FreshPaws",
        "sector": "pet",
        "strategy": "consumer",
        "stage": "screening",
        "description": "Premium fresh pet food delivery. Subscription model with 70% retention at 12 months.",
        "deal_size": 60_000_000,
        "valuation": 250_000_000,
        "revenue": 48_000_000,
        "growth_rate": 62,
        "source": "JP Morgan referral",
        "lead_contact": "Mike Torres",
        "priority": "high",
        "notes": "Competitive process. Need to move quickly.",
        "days_ago": 3,
    },
    {
        "company_name": "BrewHaus",
        "sector": "food-bev",
        "strategy": "consumer",
        "stage": "screening",
        "description": "Non-alcoholic craft beer brand. #1 NA beer on Amazon. Expanding into retail.",
        "deal_size": 35_000_000,
        "valuation": 140_000_000,
        "revenue": 22_000_000,
        "growth_rate": 120,
        "source": "Industry conference",
        "lead_contact": "Lisa Park",
        "priority": "medium",
        "notes": "NA beer category growing 30%+ YoY. Category dynamics favorable.",
        "days_ago": 8,
    },
    {
        "company_name": "Nomad Analytics",
        "sector": "software",
        "strategy": "technology",
        "stage": "screening",
        "description": "AI-powered supply chain optimization for mid-market brands. Integrates with Shopify, NetSuite.",
        "deal_size": 25_000_000,
        "valuation": 120_000_000,
        "revenue": 15_000_000,
        "growth_rate": 95,
        "source": "Portfolio company referral",
        "lead_contact": "David Kim",
        "priority": "medium",
        "notes": "Several portfolio companies could be customers. Strong strategic fit.",
        "days_ago": 12,
    },
    # Diligence stage - deep dives
    {
        "company_name": "Vive Wellness",
        "sector": "wellness",
        "strategy": "consumer",
        "stage": "diligence",
        "description": "Adaptogen-based functional beverages. Available in 8,000 doors including Whole Foods, Sprouts.",
        "deal_size": 75_000_000,
        "valuation": 320_000_000,
        "revenue": 58_000_000,
        "growth_rate": 55,
        "source": "Goldman Sachs",
        "lead_contact": "Sarah Chen",
        "priority": "high",
        "notes": "Commercial DD complete. Consumer panel results strong. Working on financial model.",
        "days_ago": 18,
    },
    {
        "company_name": "Luma Beauty",
        "sector": "beauty",
        "strategy": "consumer",
        "stage": "diligence",
        "description": "Prestige skincare brand. Celebrity founder with genuine product development involvement. Sephora exclusive.",
        "deal_size": 100_000_000,
        "valuation": 450_000_000,
        "revenue": 85_000_000,
        "growth_rate": 42,
        "source": "Jefferies",
        "lead_contact": "Mike Torres",
        "priority": "high",
        "notes": "Management meetings complete. Supply chain review underway. Strong gross margins (72%).",
        "days_ago": 25,
    },
    {
        "company_name": "DataMesh",
        "sector": "software",
        "strategy": "technology",
        "stage": "diligence",
        "description": "Real-time consumer data platform for CPG brands. 140% net revenue retention.",
        "deal_size": 30_000_000,
        "valuation": 150_000_000,
        "revenue": 18_000_000,
        "growth_rate": 78,
        "source": "Proprietary sourcing",
        "lead_contact": "David Kim",
        "priority": "medium",
        "notes": "Technical DD scheduled. Customer references all strong. CAC payback < 12 months.",
        "days_ago": 15,
    },
    {
        "company_name": "Wild Root Provisions",
        "sector": "food-bev",
        "strategy": "consumer",
        "stage": "diligence",
        "description": "Organic snack platform. Two brands with combined $40M revenue. Strong velocity in natural channel.",
        "deal_size": 55_000_000,
        "valuation": 200_000_000,
        "revenue": 40_000_000,
        "growth_rate": 35,
        "source": "Piper Sandler",
        "lead_contact": "Lisa Park",
        "priority": "medium",
        "notes": "Unit economics attractive. Potential for channel expansion into conventional grocery.",
        "days_ago": 22,
    },
    # IC Review stage
    {
        "company_name": "Radiant Labs",
        "sector": "beauty",
        "strategy": "consumer",
        "stage": "ic_review",
        "description": "Clinical skincare brand with dermatologist-backed formulations. #1 on Dermstore. Expanding to Ulta.",
        "deal_size": 80_000_000,
        "valuation": 350_000_000,
        "revenue": 65_000_000,
        "growth_rate": 48,
        "source": "Lazard",
        "lead_contact": "Sarah Chen",
        "priority": "high",
        "notes": "IC memo drafted. Thesis: category leader in clinical skincare with proven DTC-to-retail playbook. Key risk: Ulta rollout execution.",
        "days_ago": 30,
    },
    {
        "company_name": "PetVet Connect",
        "sector": "pet",
        "strategy": "technology",
        "stage": "ic_review",
        "description": "Telehealth platform for veterinary care. 500K+ registered pets. B2B2C model with vet clinics.",
        "deal_size": 20_000_000,
        "valuation": 95_000_000,
        "revenue": 12_000_000,
        "growth_rate": 110,
        "source": "Board member referral",
        "lead_contact": "David Kim",
        "priority": "high",
        "notes": "IC presentation Thursday. Strong unit economics. TAM expanding as pet humanization continues.",
        "days_ago": 35,
    },
    # Term Sheet stage
    {
        "company_name": "Sol Provisions",
        "sector": "food-bev",
        "strategy": "consumer",
        "stage": "term_sheet",
        "description": "Premium Mexican-inspired CPG brand. Salsas, sauces, seasonings. Strong brand with authentic story.",
        "deal_size": 65_000_000,
        "valuation": 280_000_000,
        "revenue": 52_000_000,
        "growth_rate": 38,
        "source": "William Blair",
        "lead_contact": "Mike Torres",
        "priority": "high",
        "notes": "Term sheet delivered. Exclusivity granted through March 25. Legal DD in progress.",
        "days_ago": 40,
    },
    {
        "company_name": "FlexStack",
        "sector": "software",
        "strategy": "technology",
        "stage": "term_sheet",
        "description": "Composable commerce platform for mid-market brands. Headless architecture with pre-built integrations.",
        "deal_size": 35_000_000,
        "valuation": 175_000_000,
        "revenue": 22_000_000,
        "growth_rate": 65,
        "source": "Qatalyst Partners",
        "lead_contact": "David Kim",
        "priority": "high",
        "notes": "Term sheet signed. Final legal review. Closing targeted end of Q1.",
        "days_ago": 45,
    },
    # Closed - recently completed
    {
        "company_name": "Aura Botanicals",
        "sector": "wellness",
        "strategy": "consumer",
        "stage": "closed",
        "description": "CBD-free plant-based wellness brand. Supplements, topicals, teas. Strong Amazon presence.",
        "deal_size": 50_000_000,
        "valuation": 210_000_000,
        "revenue": 38_000_000,
        "growth_rate": 45,
        "source": "Harris Williams",
        "lead_contact": "Sarah Chen",
        "priority": "high",
        "notes": "Closed Feb 2026. 100-day plan in execution. First board meeting scheduled.",
        "days_ago": 55,
    },
    # Passed - decided not to pursue
    {
        "company_name": "QuickBite",
        "sector": "food-bev",
        "strategy": "consumer",
        "stage": "passed",
        "description": "Meal kit delivery for single-serving portions. High growth but unit economics challenged.",
        "deal_size": 40_000_000,
        "valuation": 160_000_000,
        "revenue": 28_000_000,
        "growth_rate": 70,
        "source": "Morgan Stanley",
        "lead_contact": "Lisa Park",
        "priority": "low",
        "notes": "Passed: Customer acquisition costs unsustainable at scale. Gross margins below 30%. Category headwinds.",
        "days_ago": 60,
    },
    {
        "company_name": "Byte Commerce",
        "sector": "marketplace",
        "strategy": "technology",
        "stage": "passed",
        "description": "Social commerce marketplace for artisan goods. Beautiful product but monetization unclear.",
        "deal_size": 15_000_000,
        "valuation": 80_000_000,
        "revenue": 5_000_000,
        "growth_rate": 150,
        "source": "Proprietary sourcing",
        "lead_contact": "David Kim",
        "priority": "low",
        "notes": "Passed: Revenue quality concerns. High GMV but low take rate. Path to profitability unclear.",
        "days_ago": 50,
    },
    {
        "company_name": "Zenith Supplements",
        "sector": "wellness",
        "strategy": "consumer",
        "stage": "screening",
        "description": "Performance nutrition brand targeting CrossFit and functional fitness communities. Strong ambassador program.",
        "deal_size": 30_000_000,
        "valuation": 130_000_000,
        "revenue": 20_000_000,
        "growth_rate": 55,
        "source": "Founder outreach",
        "lead_contact": "Mike Torres",
        "priority": "medium",
        "notes": "Initial review. Interesting community-driven growth model. Need to assess TAM ceiling.",
        "days_ago": 2,
    },
    {
        "company_name": "RetailOS",
        "sector": "software",
        "strategy": "technology",
        "stage": "diligence",
        "description": "Unified retail operations platform. POS + inventory + CRM for multi-location brands.",
        "deal_size": 28_000_000,
        "valuation": 140_000_000,
        "revenue": 16_000_000,
        "growth_rate": 72,
        "source": "Raymond James",
        "lead_contact": "David Kim",
        "priority": "medium",
        "notes": "Customer interviews underway. Product fits well with VMG consumer portfolio needs.",
        "days_ago": 20,
    },
]


def seed():
    db = SessionLocal()
    try:
        # Clear existing
        db.query(PipelineDeal).delete()
        db.commit()

        now = datetime.utcnow()
        for deal_data in DEALS:
            days_ago = deal_data.pop("days_ago")
            deal = PipelineDeal(
                id=uuid.uuid4(),
                company_name=deal_data["company_name"],
                sector=deal_data["sector"],
                stage=deal_data["stage"],
                strategy=deal_data["strategy"],
                description=deal_data["description"],
                deal_size=deal_data["deal_size"],
                valuation=deal_data["valuation"],
                revenue=deal_data["revenue"],
                growth_rate=deal_data["growth_rate"],
                source=deal_data["source"],
                lead_contact=deal_data["lead_contact"],
                priority=deal_data["priority"],
                notes=deal_data["notes"],
                entered_pipeline=now - timedelta(days=days_ago + random.randint(5, 30)),
                last_activity=now - timedelta(days=days_ago),
            )
            db.add(deal)

        db.commit()
        print(f"Seeded {len(DEALS)} pipeline deals")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
